const APPLICATION_STATUS = Object.freeze({
  APPLICATION_COMPLETION: 'APPLICATION_COMPLETION',
  DOCUMENT_PASS: 'DOCUMENT_PASS',
  DOCUMENT_FAIL: 'DOCUMENT_FAIL',
  DOCUMENT_PASS_NOTIFICATION: 'DOCUMENT_PASS_NOTIFICATION',
  DOCUMENT_FAIL_NOTIFICATION: 'DOCUMENT_FAIL_NOTIFICATION',
  FINAL_INTERVIEW: 'FINAL_INTERVIEW',
  FINAL_PASS: 'FINAL_PASS',
  FINAL_FAIL: 'FINAL_FAIL',
  FINAL_PASS_NOTIFICATION: 'FINAL_PASS_NOTIFICATION',
  FINAL_FAIL_NOTIFICATION: 'FINAL_FAIL_NOTIFICATION',

  next : (status) => {
    switch(status) {
      case APPLICATION_STATUS.DOCUMENT_PASS:
        return APPLICATION_STATUS.FINAL_INTERVIEW;
      case APPLICATION_STATUS.DOCUMENT_FAIL:
        return APPLICATION_STATUS.DOCUMENT_FAIL_NOTIFICATION;
      case APPLICATION_STATUS.FINAL_PASS:
        return APPLICATION_STATUS.FINAL_PASS_NOTIFICATION;
      case APPLICATION_STATUS.FINAL_FAIL:
        return APPLICATION_STATUS.FINAL_FAIL_NOTIFICATION;
    }
  }
});

module.exports = APPLICATION_STATUS;
