const APPLICATION_STATUS = Object.freeze({
  APPLICATION_COMPLETION: 'APPLICATION_COMPLETION',
  DOCUMENT_PASS: 'DOCUMENT_PASS',
  DOCUMENT_FAILL: 'DOCUMENT_FAILL',
  DOCUMENT_PASS_NOTIFICATION: 'DOCUMENT_PASS_NOTIFICATION',
  DOCUMENT_FAILL_NOTIFICATION: 'DOCUMENT_FAILL_NOTIFICATION',
  FINAL_INTERVIEW: 'FINAL_INTERVIEW',
  FINAL_PASS: 'FINAL_PASS',
  FINAL_FAIL: 'FINAL_FAIL',
  FINAL_PASS_NOTIFICATION: 'FINAL_PASS_NOTIFICATION',
  FINAL_FAIL_NOTIFICATION: 'FINAL_FAIL_NOTIFICATION',
});

module.exports = APPLICATION_STATUS;
